---
version: '3'

services:

  traefik:
    image: traefik:latest
    command: --web --docker --docker.watch --docker.domain=${DOMAIN} \
             --docker.exposedbydefault=false --acme.domains=${DOMAIN}
    container_name: traefik
    hostname: traefik
    ports:
      - "442:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG}/traefik/acme.json:/acme.json
      - ${CONFIG}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${CONFIG}/traefik/.htpasswd:/etc/traefik/.htpasswd:ro
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:monitor.${DOMAIN}"
      traefik.port: "8080"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: always

  watchtower:
    image: v2tec/watchtower:latest
    command: --cleanup --label-enable --schedule="0 2 * * *"
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always

  nzbget:
    image: danofun/nzbget
    container_name: nzbget
    hostname: nzbget
    ports:
      - "6789:6789"
    volumes:
      - ${CONFIG}/nzbget:/config
      - ${MEDIA}/downloads/nzbget:/media/downloads/nzbget
      - ${MEDIA}/music/unsorted:/media/music/unsorted
      - ${MEDIA}/apps:/media/apps
      - ${MEDIA}/games/PC/ISO:/media/games/PC/ISO
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always

  sonarr:
    image: lsiodev/sonarr-preview
    container_name: sonarr
    hostname: sonarr
    ports:
      - "8989:8989"
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${MEDIA}/downloads:/media/downloads
      - ${MEDIA}/tv:/media/tv
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    ports:
      - "7878:7878"
    volumes:
      - ${CONFIG}/radarr:/config
      - ${MEDIA}/downloads:/media/downloads
      - ${MEDIA}/movies:/media/movies
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always

  nzbhydra:
    image: linuxserver/hydra2:latest
    container_name: nzbhydra
    hostname: nzbhydra
    ports:
      - "5076:5076"
    volumes:
      - ${CONFIG}/nzbhydra2:/config
      - ${MEDIA}/downloads:/media/downloads
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always

  plex:
    image: plexinc/pms-docker
    container_name: plex
    hostname: plex
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - ${CONFIG}/plex:/config
      - ${MEDIA}/tv:/media/tv
      - ${MEDIA}/movies:/media/movies
      - ${MEDIA}/music:/media/music
      - ${MEDIA}/workouts:/media/workouts
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    devices:
      - /dev/dri:/dev/dri
    labels:
      traefik.enable: "true"
      traefik.port: "32400"
      traefik.frontend.rule: "Host:plex.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: always

  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    ports:
      - "8181:8181"
    volumes:
      - ${CONFIG}/tautulli:/config
      - ${CONFIG}/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:seafile.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: always

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    hostname: ombi
    ports:
      - "3579:3579"
    volumes:
      - ${CONFIG}/ombi:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:requests.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    
  unifi:
    image: linuxserver/unifi:unstable
    container_name: unifi
    hostname: unifi
    ports:
      - "3478:3478"
      - "10001:10001"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "6788:6789"
    volumes:
      - ${CONFIG}/unifi:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    
  tvheadend:
    image: linuxserver/tvheadend
    container_name: tvheadend
    hostname: tvheadend
    ports:
      - "9981:9981"
      - "9982:9982"
    volumes:
      - ${CONFIG}/tvheadend:/config
      - ${MEDIA}/tvheadend/recordings:/recordings
      - ${MEDIA}/tvheadend/timeshift:/timeshift
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:tv.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: always

  bitwarden:
    image: mprasil/bitwarden
    container_name: bitwarden
    hostname: bitwarden
    ports:
      - "8343:80"
    volumes:
      - ${CONFIG}/bitwarden:/data
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:passwords.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    
  beets:
    image: linuxserver/beets
    container_name: beets
    hostname: beets
    ports:
      - "8337:8337"
    volumes:
      - ${CONFIG}/beets:/config
      - ${MEDIA}/music:/media/music
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    hostname: radicale
    ports:
      - "5232:5232"
    volumes:
      - ${CONFIG}/radicale/config:/config
      - ${CONFIG}/radicale/data:/data
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:dav.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    
  seafile:
    image: seafileltd/seafile:latest
    container_name: seafile
    hostname: seafile
    ports:
      - "9080:80"
    volumes:
      - ${CONFIG}/seafile/db:/shared/db
      - ${CONFIG}/seafile/logs:/shared/logs
      - ${SEAFILE}:/shared/seafile      
    environment:
      SEAFILE_SERVER_HOSTNAME: 'https://seafile.peakconsults.com'
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:seafile.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: always

  deluge:
    image: binhex/arch-delugevpn
    container_name: deluge
    hostname: deluge
    cap_add:
      - NET_ADMIN
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
      - "8118:8118"
    volumes:                                                                                                 
      - ${CONFIG}/deluge:/config
      - ${MEDIA}/downloads/deluge:/data                                                                 
    environment:                                                                                             
      - VPN_ENABLED=yes                                                                       
      - VPN_USER=${OVPNUSER}
      - VPN_PASS=${OVPNPASS}
      - VPN_PROV=custom
      - VPN_OPTIONS=
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=10.0.14.0/24
      - NAME_SERVERS=209.222.18.222,37.235.1.174,1.1.1.1,8.8.8.8,209.222.18.218,37.235.1.177,1.0.0.1,8.8.4.4
      - DEBUG=false
      - UMASK=000
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      com.centurylinklabs.watchtower.enable: "true"                                                          
    restart: always                                                                                  

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    hostname: onlyoffice
    ports:
      - "9081:80"
    volumes:
      - ${CONFIG}/onlyoffice/logs:/var/log/onlyoffice
      - ${CONFIG}/onlyoffice/data:/var/www/onlyoffice/Data
      - ${CONFIG}/onlyoffice/lib:/var/lib/onlyoffice
      - ${CONFIG}/onlyoffice/db:/var/lib/postgresql
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:office.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: always

  fxsync:
    image: mozilla/syncserver:latest
    container_name: fxsync
    hostname: fxsync
    ports:
      - "4500:4500"
    volumes:
      - ${CONFIG}/firefox-syncserver:/tmp
    environment:
      - SYNCSERVER_PUBLIC_URL=https://fxsync.${DOMAIN}
      - SYNCSERVER_SECRET=${FXSECRET}
      - SYNCSERVER_SQLURI=sqlite:////tmp/syncserver.db
      - SYNCSERVER_BATCH_UPLOAD_ENABLED=true
      - SYNCSERVER_FORCE_WSGI_ENVIRON=false
      - SYNCSERVER_ALLOW_NEW_USER=true
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:fxsync.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: always