---
version: '3'

services:

  traefik:
    image: traefik:latest
    command: --web --docker --docker.watch --docker.domain=${DOMAIN} \
             --docker.exposedbydefault=false --acme.domains=${DOMAIN}
    container_name: traefik
    hostname: traefik
    ports:
      - "442:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG}/traefik/acme.json:/acme.json
      - ${CONFIG}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${CONFIG}/traefik/.htpasswd:/etc/traefik/.htpasswd:ro
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:monitor.${DOMAIN}"
      traefik.port: "8080"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  watchtower:
    image: v2tec/watchtower:latest
    command: --cleanup --label-enable --schedule="0 2 * * *"
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    hostname: nzbget
    ports:
      - "6789:6789"
    volumes:
      - ${CONFIG}/nzbget:/config
      - ${MEDIA}/downloads/nzbget:/media/downloads/nzbget
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  sonarr:
    image: lsiodev/sonarr-preview
    container_name: sonarr
    hostname: sonarr
    ports:
      - "8989:8989"
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${MEDIA}/downloads:/media/downloads
      - ${MEDIA}/tv:/media/tv
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    ports:
      - "7878:7878"
    volumes:
      - ${CONFIG}/radarr:/config
      - ${MEDIA}/downloads:/media/downloads
      - ${MEDIA}/movies:/media/movies
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  nzbhydra:
    image: linuxserver/hydra2:latest
    container_name: nzbhydra
    hostname: nzbhydra
    ports:
      - "5076:5076"
    volumes:
      - ${CONFIG}/nzbhydra2:/config
      - ${MEDIA}/downloads:/media/downloads
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: plex
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "1900:1900/udp"
    volumes:
      - ${CONFIG}/plex:/config
      - ${MEDIA}/tv:/media/tv
      - ${MEDIA}/movies:/media/movies
      - ${MEDIA}/music:/media/music
      - ${MEDIA}/workouts:/media/workouts
    environment:
      - PGID
      - PUID
      - TZ
      - VERSION=latest
    devices:
      - /dev/dri:/dev/dri
    labels:
      traefik.enable: "true"
      traefik.port: "32400"
      traefik.frontend.rule: "Host:plex.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    ports:
      - "8181:8181"
    volumes:
      - ${CONFIG}/tautulli:/config
      - ${CONFIG}/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    hostname: ombi
    ports:
      - "3579:3579"
    volumes:
      - ${CONFIG}/ombi:/config
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "3579"
      traefik.frontend.rule: "Host:requests.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    
  unifi:
    image: linuxserver/unifi:unstable
    container_name: unifi
    hostname: unifi
    ports:
      - "3478:3478"
      - "10001:10001"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "6788:6789"
    volumes:
      - ${CONFIG}/unifi:/config
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    
  tvheadend:
    image: linuxserver/tvheadend
    container_name: tvheadend
    hostname: tvheadend
    ports:
      - "9981:9981"
      - "9982:9982"
    volumes:
      - ${CONFIG}/tvheadend:/config
      - ${MEDIA}/tvheadend/recordings:/recordings
      - ${MEDIA}/tvheadend/timeshift:/timeshift
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "9981"
      traefik.frontend.rule: "Host:tv.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  bitwarden:
    image: mprasil/bitwarden
    container_name: bitwarden
    hostname: bitwarden
    ports:
      - "8343:80"
    volumes:
      - ${CONFIG}/bitwarden:/data
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host:passwords.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    
  beets:
    image: linuxserver/beets
    container_name: beets
    hostname: beets
    ports:
      - "8337:8337"
    volumes:
      - ${CONFIG}/beets:/config
      - ${MEDIA}/music:/media/music
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    hostname: radicale
    ports:
      - "5232:5232"
    volumes:
      - ${CONFIG}/radicale/config:/config
      - ${CONFIG}/radicale/data:/data
    labels:
      traefik.enable: "true"
      traefik.port: "5232"
      traefik.frontend.rule: "Host:dav.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    
  seafile:
    image: foxel/seafile
    container_name: seafile
    hostname: seafile
    ports:
      - "9080:80"
    volumes:
      - ${SEAFILE}:/seafile
    environment:
      SEAFILE_URL: 'https://seafile.peakconsults.com'
    links:
      - mysql
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host:seafile.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    volumes:
      - ${CONFIG}/mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    hostname: transmission
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 1.1.1.1                                                                                              
      - 1.0.0.1                                                                                              
    volumes:                                                                                                 
      - ${CONFIG}/transmission:/config
      - ${MEDIA}/downloads/transmission:/data                                                                 
    environment:                                                                                             
      - OPENVPN_PROVIDER=${OVPNSERVER}                                                                        
      - OPENVPN_USERNAME=${OVPNUSER}
      - OPENVPN_PASSWORD=${OVPNPASS}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mssfix 1450
      - LOCAL_NETWORK=10.0.14.0/24
      - OPENVPN_CONFIG=${OVPNCONFIG}
      - WEBPROXY_ENABLED=true
      - PGID
      - PUID
      - TZ
    labels:
      com.centurylinklabs.watchtower.enable: "true"                                                          
    restart: unless-stopped                                                                                  

  transmission-rss:
    image: haugene/transmission-rss                                                                          
    container_name: transmission-rss
    hostname: transmission-rss
    links:
      - transmission
    environment:
      - RSS_URL=<URL>
      - PGID
      - PUID                                                                                                 
      - TZ
    labels:                                                                                                  
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    hostname: onlyoffice
    ports:
      - "9081:80"
    volumes:
      - ${CONFIG}/onlyoffice:/var/log/onlyoffice
      - ${CONFIG}/onlyoffice:/var/www/onlyoffice/Data
      - ${CONFIG}/onlyoffice:/var/lib/onlyoffice
      - ${CONFIG}/onlyoffice:/var/lib/postgresql
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host:office.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
